DROP TABLE STUDENTS;
DROP TABLE COURSES;
DROP TABLE STUDENT_COURSE;

CREATE TABLE STUDENTS(
  ID INTEGER PRIMARY KEY,
  FIRSTNAME VARCHAR(50),
  LASTNAME  VARCHAR(50)
);

CREATE TABLE COURSES(
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250)
);

CREATE TABLE STUDENT_COURSE
(
  STUDENTID INT,
  COURSEID INT,
  CONSTRAINT STUDENT_COURSE_pk PRIMARY KEY (STUDENTID, COURSEID),
  CONSTRAINT STUDENT_COURSE_STUDENTS_STUDENTID_fk FOREIGN KEY (STUDENTID) REFERENCES STUDENTS (ID) ON DELETE CASCADE,
  CONSTRAINT STUDENT_COURSE_COURSEID_fk FOREIGN KEY (COURSEID) REFERENCES COURSES (ID) ON DELETE CASCADE
);

