INSERT INTO STUDENTS VALUES(1, 'John', 'Smith');
INSERT INTO STUDENTS VALUES(2, 'Alice', 'Bloggs');
INSERT INTO STUDENTS VALUES(3, 'Bob', 'Jones');

INSERT INTO COURSES VALUES(1, 'Biology', 'Introduction to Biology');
INSERT INTO COURSES VALUES(2, 'Chemistry', 'Introduction to Chemistry');
INSERT INTO COURSES VALUES(3, 'History', 'Introduction to History');

INSERT INTO STUDENT_COURSE VALUES (1, 1);
INSERT INTO STUDENT_COURSE VALUES (1, 3);
INSERT INTO STUDENT_COURSE VALUES (2, 1);
INSERT INTO STUDENT_COURSE VALUES (2, 2);